name: Run SEX Script

on:
  workflow_dispatch:

jobs:
  run-rdp:
    runs-on: windows-latest
    timeout-minutes: 0  # Không đặt timeout cụ thể, chạy bao lâu thì chạy
    steps:
      - name: Run argo_tunnel.ps1 from GitLab
        shell: powershell
        run: |
          iwr -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/argo_tunnel.ps1" -OutFile "argo_tunnel.ps1"
          powershell -ExecutionPolicy Bypass -File .\argo_tunnel.ps1
