name: Start Ubuntu RDP Session

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 0  # Tối đa GitHub cho phép (6 tiếng)

    steps:
      - name: Download RDP script and fix line endings
        run: |
          curl -fsSL https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/ubuntu_rdp.sh -o rdp.sh
          sudo sed -i 's/\r$//' rdp.sh
          bash rdp.sh

      - name: Keep runner alive
        run: tail -f /dev/null
